### ISSUE TITLE
Prevent page splits in pre-assessment print view

### ISSUE THREAD

**Issue by jonshaffer** [jonshaffer/wgu-extension#2]
This CSS will prevent splitting of questions and answers on the pre-assessment print view.

```css
@media print {
    .cr-question {
        break-inside: avoid;
    }
}
```

URL:

https://my.wgu.edu/coaching-report/preassessment-report/v1/studentPidm/{studentNumberId}/assessmentCode/{code}/testDate/{numberDateTime}
